name: sisepuede
channels:
  - conda-forge
dependencies:
  - python=3.11
# - julia=0.6.0 -- have to install after julia, performed in Docker multi-stage build
  - geopy=2.1.0
  - munch=2.5.0
  - numpy=1.23.5
# - openpyxl=3.0.10
  - pandas=2.2.1
  - pyDOE2=1.3.0
  - PyYAML=6.0
  - SQLAlchemy=2.0.29
  - XlsxWriter=3.2.0
